POST http://localhost:2020/createUser
content-type: application/json

{
    "firstName": "Ali",
    "lastName": "Ghieth",
    "email": "ahmed@gmail.com5s",
    "gender": "Female",
    "userName": "abdoAli25",
    "password": "123",
    "role": "Instructor"
}