POST http://localhost:2020/createCourse
content-type: application/json

 {
     "title": "csen55",
     "subtitle": "sdgfdfggggggggggggggggggggggggggg",
     "subject": "csen",
     "price": "125",
     "username":"abdoAli25",
     "totalHours": "25",
     "image": "ddddddddddddddddddddddddd",
     "video": "asdglgllllllfasdgdas",
     "prerequisite":"fjdskla;ggsfm;lgasldga",
     "summary":"dasfglkdgsldgdagsldg"
 } 